theme:
  name: material
  features:
    - navigation.indexes
    - navigation.tabs
    - navigation.sections
  palette:
    scheme: default
  custom_dir: docs/theme_override_home/
  # logo: assets/logo.png
  # favicon: assets/images/favicon.ico
site_name: Kimmo's blog
site_url: https://kimmosaaskilahti.fi
docs_dir: docs
# repo_url: https://github.com/ksaaskil/kimmosaaskilahti.fi
extra_css:
  - stylesheets/extra.css
nav:
  - Home:
      - Home: index.md
  - Blog:
      - blog/index.md
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - tables
  - toc:
      toc_depth: 3
plugins:
  - blog:
      post_excerpt: required
extra:
  analytics:
    provider: google
    property: !ENV GA_TRACKING_ID
