[project]
name = "kimmosaaskilahti-fi"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "mkdocs>=1.6.1",
    "mkdocs-glightbox>=0.4.0",
    "mkdocs-material==9.5.49",
    "pillow>=11.3.0",
    "pre-commit>=4.2.0",
]
